baseURL = "/"
languageCode = "en-us"
title = "OCD-NET"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
 # google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "OCD-NET is an internet-delivered cognitive behaviour therapy developed by researchers at Karolinska Institutet in Stockholm, Sweden."
    meta_og_title = "OCD-NET"
    meta_og_type = "website"
    meta_og_url = "https://ocd-net.com"
    meta_og_image = ""
    meta_og_description = ""


[[menu.main]]
	name = "About OCD-NET"
	url = "/about-ocd-net/"
    weight = 1

[[menu.main]]
    name = "Explore"
    url = "/explore/"
    weight = 2

[[menu.main]]
    name = "Meet the team"
    url = "/meet-the-team/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"